version: "3"

services:

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_MONGODB_URL: "mongodb://admin:password@mongo:27017"

  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: malta
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - 'postgres:/var/lib/postgresql/data:rw'

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: local@localhost.local
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres:
  mongo:
  pgadmin: